### ISSUE TITLE
When using the polylang plugin, the order status for "notifications" is not updated

### ISSUE THREAD

**Issue by GOTsi** [eMerchantPay/woocommerce-emp-plugin#5]
When using the polylang plugin, the order status for "notifications" is not updated, it returns a 403 code. I made a fix, you need to add these two lines of code

'lang' => '',
'suppress_filters' => true,

to file

classes/wc_emerchantpay_order_helper.php

https://prnt.sc/xGWXZxJpdDUx

**Comment by dyd** [comment]
Hello @GOTsi,

We tried to reproduce the reported case with no success. May I ask you to provide us with a bit more information about it?
 
 We used:
* [Polylang](https://wordpress.org/plugins/polylang/) 3.4.5
* WordPress 6.3.1
* WooCommerce 8.0.3

Can you provide us with your environment setup in order to re-present the case, please?

**Comment by GOTsi** [comment]
Hi,

- Polylang 3.4.5 
- WooCommerce 8.0.3
- WooCommerce emerchantpay Payment Gateway Client 1.14.3 

- If there are several languages ​​in the polylang, and make an order from a non-default language, emerchant notification will not find the order and will return this 403 response https://prnt.sc/Mc9eqBzie1es

- If you place an order using the woocommerce api and pay using the generated payment link, the situation will be the same.

This happens because WP_Query searches with the language that is currently set - and for notifications it is the default, and the order we need is in a different language and payment identifier transaction_unique_id.

And also plugins can add their own filters and that again does not allow you to find the our order.

My modified get_order_id function https://prnt.sc/PX1nooTXnuht

**Comment by dyd** [comment]
Hello @GOTsi,

We made a further investigation. We met only one case where we can admit that there is a compatibility issue with the Polylang plugin. The case when `Hide URL language information for default language` is turned off.

In every other case, we have normal payment processing. Unfortunately, we are not going to add a solution for this case, because it is most likely not a problem in the emerchantpay Payment Plugin. The WooCommerce `api_request_url` method doesn't include language or maybe there should be no language.

Anyway, If this is your case you can add this piece to your platform:
```
add_filter('woocommerce_api_request_url', function($api_request_url, $request, $ssl) {
	// Suit $api_request_url to fit your case
	// For example replace /wc-api/ with /<language>/wc-api/
}, 10, 3);
``` 

I hope this helps. If this is not your case, let us know.
